[api]
    dashboard = true
    debug = true
    insecure = true
[providers.docker]
    exposedByDefault = true
    swarmMode = true
    network = "proxynetwork"
[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web-secure]
        address = ":443"