name: docker
on:
    - push
jobs:
    makefile:
        runs-on: ubuntu-latest
        steps:
            - {name: Checkout, uses: actions/checkout@v2}
            - {name: 'Docker swarm init', run: 'docker swarm init --default-addr-pool 10.20.0.0/16'}
            - {name: 'Create proxy network', run: 'make create-network'}
            - {name: 'Show HELP', run: 'make help'}
            - {name: 'Build containers', run: 'make deploy'}
            - {name: 'Check running stack', run: 'docker stack ls'}
            - {name: 'Make sleep', run: 'make sleep'}
            - {name: 'Installation version PROD', run: 'make env-prod'}
            - {name: 'Check running containers', run: 'docker service ls'}
            - {name: 'BDD MIGRATE', run: 'make bdd-migrate'}
            - {name: 'Run the fixtures', run: 'make bdd-fixtures'}